2022-01-14 22:06:04   Arguments: Namespace(cache_refresh_rate=1000, datasets_folder='/content/pitts30k', device='cuda', epochs_num=50, exp_name='default', infer_batch_size=16, lr=1e-05, margin=0.1, neg_samples_num=1000, negs_num_per_query=10, num_workers=8, output_folder='runs/default/2022-01-14_22-06-04', patience=2, queries_per_epoch=5000, recall_values=[1, 5, 10, 20], seed=0, train_batch_size=4, train_positives_dist_threshold=8, val_positive_dist_threshold=25)
2022-01-14 22:06:04   The outputs are being saved in runs/default/2022-01-14_22-06-04
2022-01-14 22:06:04   Using 1 GPUs and 2 CPUs
2022-01-14 22:06:04   Loading dataset Pitts30k from folder /content/pitts30k
2022-01-14 22:06:04   Test set: < BaseDataset, pitts30k - #database: 10000; #queries: 6816 >
2022-01-14 22:06:05   Train only conv4 of the ResNet-18 (remove conv5), freeze the previous ones
2022-01-14 22:06:08   
Traceback (most recent call last):
  File "real_test.py", line 41, in <module>
    best_model_state_dict = torch.load("/content/drive/MyDrive/2_Gem")["model_state_dict"]
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: '/content/drive/MyDrive/2_Gem'

